---
name: Lint

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
# https://github.com/dotnet/format

#############################
# Start the job on all push #
#############################
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*' # v* trigger release.yml

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on, Container action is only supported on Linux
    runs-on: windows-latest 

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Configure git
        run: git config --global core.autocrlf false
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format --version 5.1.* --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json
      
      - name: Lint
        run: dotnet format --verify-no-changes